### ISSUE TITLE
Cannot add multiple affiliations

### ISSUE THREAD

**Issue by Crismoc** [mikemahoney218/quarto-arxiv#16]
I cannot get the pdf document to include more than one affiliation for authors, like in this reprex for one author (same happens with more authors):

```qmd
---
title: "My Title"
author:
  - name: John Doe
    affiliations:
      - name: University A
        country: US
      - name: University B
        country: UK
    email: jdoe@uni.com
format:
  arxiv-pdf:
    keep-tex: true  
    linenumbers: false
    doublespacing: true
    authorcols: true
    number-sections: false
    runninghead: "My Title"
abstract: |
  Lorem ipsum dolor sit amet.
---

# Introduction

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

And the rendered output:

![image](https://github.com/mikemahoney218/quarto-arxiv/assets/8093092/0747f99b-4e57-495f-ba1c-cfd40c902a13)

Is this a bug or should it be done differently? Thanks!

**Comment by mikemahoney218** [comment]
Thanks; fixed now:
![image](https://github.com/mikemahoney218/quarto-arxiv/assets/38229299/3263ecd7-a457-4095-8f5b-289103033055)

This was a holdover from the rticles template, but I don't think it made a ton of sense. The newest version (0.2.3) changes it so that all affiliations should be listed under all authors. 

By the way, looking at the reprex -- note that the `country` key isn't used in how authors are formatted. Only `department`, `name`, `city`, and `postal-code` are used (so the country code would be best appended to the `city` key). 

Thanks again!
